resources:
- name: ansible-deployer
  type: git
  source:
    uri: https://github.com/mohammad-dabour/ansible-concourse-docker.git
    password: {{PASS}}
    username: {{USER}}
    branch: master


- name: ansible-docker
  type: docker-image
  source:
    repository: ((reg_address)):5000/ansible
    insecure_registries: ["((reg_address)):5000"]

jobs:
- name: build-deployer
  plan:
    - get: ansible-deployer
      trigger: true
    - put: ansible-docker
      params: 
         build: ansible-deployer
         build_args:
            SSH_KEY: {{ssh_container_key}}
            USER: {{docker_user}}

